baseURL = "https://NYH-Dolphin.github.io"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
theme = "gokarna"
publishDir = "docs"
# Automatically generate robots.txt
enableRobotsTXT = true

[menu]
  [[menu.main]]
    identifier = "sharing"
    name = "Sharing"
    url = "/sharing/"
    pre = "<span data-feather='share-2'></span>"
    weight = 1

  [[menu.main]]
    identifier = "study"
    name = "Study"
    url = "/study/"
    pre = "<span data-feather='book-open'></span>"
    weight = 2

  [[menu.main]]
    identifier = "project"
    name = "Project"
    url = "/project/"
    pre = "<span data-feather='code'></span>"
    weight = 3
  
  [[menu.main]]
    identifier = "portfolio"
    name = "Itch"
    url = "https://nyh-dolphin.itch.io/"
    pre = "<span data-feather='gift'></span>"
    weight = 4

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/en/about/"
    pre = "<span data-feather='smile'></span>"
    weight = 5

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    pre = "<span data-feather='tag'></span>"
    weight = 6
  
  [[menu.main]]
    name = "中文"
    url = "../zh"
    weight = 7

  [[languages.zh.menu.main]]
    identifier = "sharing"
    name = "分享"
    url = "/sharing/"
    pre = "<span data-feather='share-2'></span>"
    weight = 1

  [[languages.zh.menu.main]]
    identifier = "study"
    name = "学习"
    url = "/study/"
    pre = "<span data-feather='book-open'></span>"
    weight = 2

  [[languages.zh.menu.main]]
    identifier = "project"
    name = "项目"
    url = "/project/"
    pre = "<span data-feather='code'></span>"
    weight = 3
  
  [[languages.zh.menu.main]]
    identifier = "portfolio"
    name = "作品"
    url = "https://nyh-dolphin.itch.io/"
    pre = "<span data-feather='gift'></span>"
    weight = 4

  [[languages.zh.menu.main]]
    identifier = "about"
    name = "关于"
    url = "/zh/about/"
    pre = "<span data-feather='smile'></span>"
    weight = 5

  [[languages.zh.menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    pre = "<span data-feather='tag'></span>"
    weight = 6

  
  [[languages.zh.menu.main]]
    name = "EN"
    url = "../en"
    weight = 7


[params]
  # URL for the avatar on homepage
  avatarURL = "/images/avatar.jpg"

  socialIcons = [
      {name = "email", url = "mailto:yn2273@nyu.edu"},
      {name = "github", url = "https://github.com/NYH-Dolphin"},
      {name = "bilibili", url = "https://space.bilibili.com/13993670"},
      {name = "linkedin", url = "https://www.linkedin.com/in/yuhe-nie-021032250/"},
      
  ]

  # Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
  avatarSize = "size-l"

  # Accent color is displayed when you hover over <a> tags
  accentColor = "#00aaff"

  # You can use this to inject any HTML in the <head> tag.
  # Ideal usecase for this is to import custom js/css or add your analytics snippet
  customHeadHTML = '''
    
    <script src="https://player.lzti.com/api/player/167601724233" id="myhk" key="167601724233" m="1"></script>



    <!-- Support Letax Equation -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.3/dist/katex.min.css" integrity="sha384-KiWOvVjnN8qwAZbuQyWDIbfCLFhLXNETzBQjA/92pIowpC0d2O3nppDGQVgwd2nB" crossorigin="anonymous">

    <!-- The loading of KaTeX is deferred to speed up page rendering -->
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.15.3/dist/katex.min.js" integrity="sha384-0fdwu/T/EQMsQlrHCCHoH10pkPLlKA1jL5dFyUOvB3lfeT2540/2g6YgSi2BL14p" crossorigin="anonymous"></script>

    <!-- Katex is a math typesetting library for the web which lets you write beautiful equations.-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css" integrity="sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js" integrity="sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"></script>
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
          // customised options
          // • auto-render specific keys, e.g.:
          delimiters: [
            {left: '$$', right: '$$', display: true},
            {left: '$', right: '$', display: false},
          ],
          // • rendering keys, e.g.:
          throwOnError : false
        });
      });
    </script>

    <!-- To automatically render math in text elements, include the auto-render extension: -->
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.15.3/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"
        onload="renderMathInElement(document.body);"></script>

    <!-- Analysis -->
    <script async defer data-website-id="website-id" src="https://analytics.example.com/script.js"></script>

    <!-- Support Favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">
    <link rel="manifest" href="/favicon/site.webmanifest">
    <link rel="mask-icon" href="/favicon/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
  '''

  # Syntax Highlighting
  pygmentsStyle = "github"

  # If you want to display posts on the homepage, the options are
  # "popular" (order posts by weight), "recent" (order posts by date)
  # or "" (do not display, default option)
  showPostsOnHomePage = "recent"

  # At the bottom of a post, show the previous and next post chronologically
  togglePreviousAndNextButtons = "true"

  # Automatically generate robots.txt
  enableRobotsTXT = true

  # Footer text
  footer = "NYH-Dolphin"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false
  [markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[languages]
  [languages.en]
    languageCode = "en-us"
    title = "Dolphin NIE"
    contentDir = 'content/en'
    description = "Imagination can change anything!"

  [languages.zh]
    languageCode = "zh-cn"
    title = "聂雨荷"
    contentDir = 'content/zh'
    description = "愿想象力改变一切！"

