baseURL = "https://NYH-Dolphin.github.io"
defaultContentLanguage = "en"
languageCode = "en"

title = "Dolphin NIE"

theme = "gokarna"

publishDir = "docs"

# Automatically generate robots.txt
enableRobotsTXT = true

[menu]
  [[menu.main]]
    identifier = "sharing"
    name = "Sharing"
    url = "/sharing/"
    pre = "<span data-feather='share-2'></span>"
    weight = 1 

  [[menu.main]]
    identifier = "study"
    name = "Study"
    url = "/study/"
    pre = "<span data-feather='book-open'></span>"
    weight = 2

  [[menu.main]]
    identifier = "project"
    name = "Project"
    url = "/project/"
    pre = "<span data-feather='code'></span>"
    weight = 3

  [[menu.main]]
    identifier = "tags"
    name = "Tag"
    url = "/tags/"
    pre = "<span data-feather='tag'></span>"
    weight = 4

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 5
    pre = "<span data-feather='smile'></span>"

  # the rest of the menu are some other websites
  [[menu.main]]
    identifier = "heart"
    name = ""
    url = "https://zweb.zone/"
    weight = 6
    pre = "<span data-feather='heart'></span>"

  [[menu.main]]
    identifier = "portfolio"
    name = ""
    url = "https://nyh-dolphin.itch.io/"
    weight = 7
    pre = "<span data-feather='gift'></span>"
  
  [[menu.main]]
    identifier = "github"
    name = ""
    url = "https://github.com/NYH-Dolphin"
    weight = 8
    pre = "<span data-feather='github'></span>"
  
  [[menu.main]]
    identifier = "home"
    name = ""
    url = "https://nyh-dolphin.github.io/"
    weight = 9
    pre = "<span data-feather='home'></span>"
  

[params]
  # URL for the avatar on homepage
  avatarURL = "/images/avatar.jpg"

  socialIcons = [
      {name = "bilibili", url = "https://space.bilibili.com/13993670"},
      {name = "youtube", url = "https://www.youtube.com/channel/UCLAZemz5uumlX-gcr7HMrAA"},
      {name = "mail", url = "mailto:nieyuhe0922@qq.com"},
  ]

  # Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
  avatarSize = "size-l"

  # Description to display on homepage
  description = "Imagination Can Change Anything!"

  # Accent color is displayed when you hover over <a> tags
  accentColor = "#00aaff"

  # You can use this to inject any HTML in the <head> tag.
  # Ideal usecase for this is to import custom js/css or add your analytics snippet
  customHeadHTML = '''

    <!-- Support Letax Equation -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.3/dist/katex.min.css" integrity="sha384-KiWOvVjnN8qwAZbuQyWDIbfCLFhLXNETzBQjA/92pIowpC0d2O3nppDGQVgwd2nB" crossorigin="anonymous">

    <!-- The loading of KaTeX is deferred to speed up page rendering -->
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.15.3/dist/katex.min.js" integrity="sha384-0fdwu/T/EQMsQlrHCCHoH10pkPLlKA1jL5dFyUOvB3lfeT2540/2g6YgSi2BL14p" crossorigin="anonymous"></script>

    <!-- Katex is a math typesetting library for the web which lets you write beautiful equations.-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css" integrity="sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js" integrity="sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"></script>
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
          // customised options
          // • auto-render specific keys, e.g.:
          delimiters: [
            {left: '$$', right: '$$', display: true},
            {left: '$', right: '$', display: false},
          ],
          // • rendering keys, e.g.:
          throwOnError : false
        });
      });
    </script>

    <!-- To automatically render math in text elements, include the auto-render extension: -->
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.15.3/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"
        onload="renderMathInElement(document.body);"></script>

    <!-- Analysis -->
    <script async defer data-website-id="website-id" src="https://analytics.example.com/script.js"></script>

    <!-- Support Favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">
    <link rel="manifest" href="/favicon/site.webmanifest">
    <link rel="mask-icon" href="/favicon/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
  '''

  # Syntax Highlighting
  pygmentsStyle = "github"

  # If you want to display posts on the homepage, the options are
  # "popular" (order posts by weight), "recent" (order posts by date)
  # or "" (do not display, default option)
  showPostsOnHomePage = "recent"

  # At the bottom of a post, show the previous and next post chronologically
  togglePreviousAndNextButtons = "true"

  # Automatically generate robots.txt
  enableRobotsTXT = true

  # Footer text
  footer = "NYH-Dolphin"

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false